language: java
dist: xenial
matrix:
  include:
  - jdk: openjdk8
    env: ADDITIONAL_MAVEN_ARGS="-P jacoco -P mutation-testing coveralls:report
services:
- docker
- xvfb
install: true
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn -f my-career-aggregator/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS