language: java

dist: xenial

jdk: openjdk8

addons:
  sonarcloud:
    organization: "liuzzom-github"

services:
- docker
- xvfb

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
- mvn -f my-career-aggregator/pom.xml clean package verify -Pjacoco -Pmutation-testing sonar:sonar -Dsonar.projectKey=liuzzom_my-career