language: java

# explicit distribution specification
# to use xvfb as a service
dist: xenial

jdk: openjdk8

services:
  - docker
  - xvfb

# skip installation step
install: true

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -f my-career-aggregator/pom.xml clean verify -P jacoco,enable-coveralls 